# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Menu"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  pre = "email"
  name = "Contact Us"
  weight = 30

[[main]]
  pre = "envelope"
  name = "Email"
  parent = "Contact Us"
  url = "mailto:inquiry@shravaniholidayhome.in"
  weight = 30

[[main]]
  pre = "instagram"
  name = "Instagram"
  parent = "Contact Us"
  url = "https://www.instagram.com/shravaniholidayhome_/"
  weight = 30

[[footer]]
  name = "Privacy"
  url = "https://external-link"
