# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 2

[[main]]
  name = "Gallery"
  pageRef = "/gallery"
  weight = 3

[[main]]
  name = "Menu"
  pageRef = "/menu"
  weight = 4

[[main]]
  name = "Location"
  pageRef = "/location"
  weight = 5

[[main]]
  pre = "email"
  name = "Contact Us"
  weight = 30

[[main]]
  pre = "envelope"
  name = "Email"
  parent = "Contact Us"
  url = "mailto:inquiry@shravaniholidayhome.in"
  weight = 30

[[main]]
  pre = "instagram"
  name = "Instagram"
  parent = "Contact Us"
  url = "https://www.instagram.com/shravaniholidayhome_/"
  weight = 30

[[main]]
  pre = "globe"
  name = "Address"
  pageRef = "/contact"
  parent = "Contact Us"
  weight = 31

[[footer]]
  name = "Privacy"
  url = "https://external-link"